name: Publish repository content to website

on:
  push:
    paths:
    - '.github/workflows/**'
    - 'presentation/**'
    - 'azure/**'
    - 'docker/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Copy site content
      run: sudo apt-get update && sudo apt install azcopy -y
      env:
        AZCOPY_AUTO_LOGIN_TYPE: ${{ secrets.AZCOPY_AUTO_LOGIN_TYPE }}
        AZCOPY_SPA_APPLICATION_ID: ${{ secrets.AZCOPY_SPA_APPLICATION_ID }}
        AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}
