name: Publish repository content to website

on:
  push:
    paths:
    - '.github/workflows/**'
    - 'presentation/**'
    - 'azure/**'
    - 'docker/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Login to CLI
      run: az login --service-principal --username ${{ secrets.spn_id }} --password ${{ secrets.spn_key }} --tenant ${{ secrets.spn_tenant }}
